== Getting Started

video::sEHVJ0rqSTU[youtube, width=640, height=360]
https://youtu.be/sEHVJ0rqSTU[Getting Started Video]

. Have the Spring Security Core plug-in installed

. Make sure you've run the quick start(e.g. grails s2-quickstart com.security User Role) note the package name

. Add the Enforcer dependency:

In Grails 2 add the following to your buildConfig.groovy under the dependencies section:

----
compile ":enforcer:1.2.2"
----

In grails 3 add the following dependency to your gradle.build:

----
compile "org.grails.plugins:enforcer:1.3.2"
----

4.Run grails enforcer-quickstart <name of the package you installed spring security core under>

WARNING: This is for imports, all files will be installed to the com.security.enforcer package. Any of the files can
be moved, except the EnforcerService. Moving the EnforcerService will break the IDE integration.

5.Check the Usage section and start using Enforcer.

=== Example applications

For Grails 2:

https://github.com/virtualdogbert/testEnforcer2[GitHub testEnforcer2]

For Grails 3:

https://github.com/virtualdogbert/testEnforcer3[GitHub testEnforcer3]

https://github.com/virtualdogbert/Grails3Tutorial/tree/step_11_enforcer_plugin[GitHub Grails3Tutorial]

----
The version scheme is Major.GrailsVersion.Minor
----
