== Getting Started

. Have the Spring Security Core plug-in installed

. Make sure you've run the quick start(e.g. grails s2-quickstart com.security User Role) note the package name

. Add the Enforcer dependency:

In grails 3.3.x+ add the following dependency to your gradle.build:

----
compile "org.grails.plugins:enforcer:2.0.0"
----

In grails 3.0.x to 3.2.x, add the following dependency to your gradle.build:

----
compile "org.grails.plugins:enforcer:1.3.4"
----

In Grails 2 add the following to your buildConfig.groovy under the plug-ins section:

----
compile ":enforcer:1.2.2"
----

4.Run grails enforcer-quickstart <name of the package you installed spring security core under>

WARNING: This is for imports, all files will be installed to the com.security.enforcer package. Any of the files can
be moved, except the InstalledEnforcerService. Moving the InstalledEnforcerService will break the IDE integration.

5.Check the Usage section and start using Enforcer.

=== Example applications

For Grails 3.3.x:

https://github.com/virtualdogbert/testEnforcer33[GitHub testEnforcer33]

For Grails 3:

https://github.com/virtualdogbert/testEnforcer3[GitHub testEnforcer3]

https://github.com/virtualdogbert/Grails3Tutorial/tree/step_11_enforcer_plugin[GitHub Grails3Tutorial]

For Grails 2:

https://github.com/virtualdogbert/testEnforcer2[GitHub testEnforcer2]


----
The version scheme was Major.GrailsVersion.Minor however for 2.0.0 I broke that, and just have the latest version for Grails 3.3.x.
----
