== Introduction
____
"You've gotta ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?"Dirty Harry(1971)
____

video::S1gxqk55f2A[youtube, width=640, height=360]

The Enforcer Plugin, is a light weight, easier to maintain/extend/use, alternative to Spring Security ACL. The plugin works off of a EnforcerService
and an Enforce Ast transform, The service take s up to 3 closures, a predicate, a failure(defaults to an EnforcerException if not specified) and a
success(defaulted to a closure that returns true). The predicate is evaluated, if it returns true, the the success closure is evaluated, else the
failure closure is evaluated. With this you can enforce any business rule you want. The EnforcerService implements two traits, RoleTrait, and
DomainRoleTrait. This is so you can use the methods in the traits without injecting any extra calls to services, which makes the calls to the
service less verbose, and easier to read. The preferred method of extending the Enforcer Service is to add new methods to the traits, modify the
existing methods in the traits, or add a new trait.


The AST Transform Enforce, can be applied to a method, or a class and injects a call to the EnforcerService(usage shown in the usage section). If the AST
transform is applied to the class level it's applied to every method in the class, but can be overridden by using it at the method level, The AST transform Enforce,
is more for the aesthetic of making a clear distinction from business rules/security, and your main code, but has the same power as the EnforcerService.
From the AST transform you can call any service, and use any variable pass into the annotated method.

The Enforcer plugin was inspired by issues with Spring Security ACL, and trying to figure out a better, and more flexible way of dealing with business rules.

Also Zed Shaw's The ACL is Dead(take this with a grain of salt):

video::2723800[vimeo, width=640, height=360]
https://vimeo.com/2723800[The ACL is Dead]
