== Usage

video::vUxjOV8YmoU[youtube, width=640, height=360]
https://youtu.be/vUxjOV8YmoU[Usage Video]


=== Enforcer 2.0.0
In Grails 3.3.x, there was a change to the Groovy version that broke Enforcers compatibility with @CompileStatic, and by extension
@Transactional, because @CompileStatic now statically checks the parameters used in annotation. This lead to compilation errors. To work
around this I changed how the enforcer annotations work,so that now create a new method in the place of the original, and copy the orginal
method to a new method. So enforcer creates a wrapper proxying the ordinal method. With this I was able to apply the Transforms from
@CompileStatic and @Transactional to the original copy, Which won't have the enforcer annotation, and won't throw an compilation error.

So now in addition to the annotations Enforce, Reinforce, and ReinforceFilter, there are variations that add transactionality, static
compilation, or both. the vacations are denoted with S, for compile static, and T for Transactional. The complete list being:

* @Enforce // Original
** @EnforceS //Statically compiles the original method.
** @EnforceT //Add Transactionality to the original
** @EnforceTS //Statically compiles, and adds Transactionality to the original method.
* @Reinforce // Original
** @ReinforceS //Statically compiles the original method.
** @ReinforceT //Add Transactionality to the original
** @ReinforceTS //Statically compiles, and adds Transactionality to the original method.
* @ReinforceFilter // Original
** @ReinforceFilterS //Statically compiles the original method.
** @ReinforceFilterT  //Add Transactionality to the original
** @ReinforceFilterTS //Statically compiles, and adds Transactionality to the original method.

In addition to those annitations two more annotations were added that are the same as @Transactional and @CompileStatic, but
they won't interfear with the enforcer annotations:

* @EnforcerCompileStatic
* @EnforcerTransactional


=== Code Examples

Check to domain role for the role owner on the Sprocket domain instance for a user:

[source,groovy]
----
def enforcerService
enforcerService.enforce({ hasDomainRole('owner', sprocket, testUser) })
----

Checks to see if the test user has the Role ROLE_USER:

[source,groovy]
----
def enforcerService
enforcerService.enforce({ hasRole('ROLE_USER', testUser) })
----

Those same checks on a method using @Enforce:

[source,groovy]
----
@Enforce({hasRole('ROLE_USER', testUser)  && hasDomainRole('owner', sprocket, testUser)})
def someMethod(){
    //some logic
}
----

Or the same check using Reinforce:

[source,groovy]
----
@Reinforce({hasRole('ROLE_USER', testUser)  && hasDomainRole('owner', sprocket, testUser)})
def someMethod(){
    //some logic
}
----

An example of ReinforceFilter which takes the original value that would be returned, and the result of the closure will
take that returned values place, be careful that that returned value of the closure matches the returned value of the
method, if you are not using def:

[source,groovy]
----
@ReinforceFilter({ Object o -> (o as List).findResults { it % 2 == 0 ? it : null } })
    List<Integer> reinforceFilter() {
        [1, 2, 3, 4, 5, 6, 7, 8, 9]
    }
----


For More examples check out the unit tests:

* https://github.com/virtualdogbert/testEnforcer33/blob/master/server/src/test/groovy/services/com/security/enforcer/EnforcerTestTServiceSpec.groovy[EnforcerTestTServiceSpec.groovy]
* https://github.com/virtualdogbert/testEnforcer33/blob/master/server/src/test/groovy/services/com/security/enforcer/EnforcerServiceSpec.groovy[EnforcerServiceSpec.groovy]
* https://github.com/virtualdogbert/testEnforcer33/blob/master/server/src/test/groovy/services/com/security/enforcer/EnforcerAnnotationSpec.groovy[EnforcerAnnotationSpec.groovy]
* https://github.com/virtualdogbert/testEnforcer33/blob/master/server/src/test/groovy/services/com/security/enforcer/ReinforceAnnotationSpec.groovy[ReinforceAnnotationSpec.groovy]

And the Integration tests:

* https://github.com/virtualdogbert/testEnforcer33/blob/master/server/src/integration-test/groovy/services/com/security/enforcer/EnforcerTestTIntegrationServiceSpec.groovy[EnforcerTestTIntegrationServiceSpec.groovy]
* https://github.com/virtualdogbert/testEnforcer33/blob/master/server/src/integration-test/groovy/services/com/security/enforcer/EnforcerTestTSServiceSpec.groovy[EnforcerTestTSServiceSpec.groovy]